### ISSUE TITLE
Changing the max sequence length in run_classifier.py results in list index out of range

### ISSUE THREAD

**Issue by Crista23** [zihangdai/xlnet#179]
Changing the max_sequence_length from 512 to 64 in run_classifier.py results in the error below:

         Traceback (most recent call last):
              File "run_classifier.py", line 855, in <module>
              tf.app.run()
              File "/home/garbacea/tf_bert2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
              _sys.exit(main(argv))
              File "run_classifier.py", line 797, in main
              for key, val in sorted(eval_results[0].items(), key=lambda x: x[0]):
              IndexError: list index out of range

**Comment by ardofski** [comment]
I have the same problem, do you use the all data or just a small subset of the data to test ?
