### ISSUE TITLE
run_squad.py shows keyerror: 'answers'

### ISSUE THREAD

**Issue by JeevaTM** [zihangdai/xlnet#197]
I ran the run_squad.py o do both training and prediction. Train was successful and upto model.ckpt-8000 have been saved in the bucket but during predictions it showed an error 'keyerror: "answers"'

I ran the run_squad.py again using the following flags. 
```
python run_squad.py \
  --use_tpu=True \
  --tpu=${TPU_NAME} \
  --num_hosts=1 \
  --num_core_per_host=8 \
  --model_config_path=${INIT_CKPT_DIR}/xlnet_config.json \
  --spiece_model_file=${INIT_CKPT_DIR}/spiece.model \
  --output_dir=${GS_PROC_DATA_DIR} \
  --init_checkpoint=${GS_INIT_CKPT_DIR}/model.ckpt-8000 \
  --model_dir=${GS_MODEL_DIR} \
  --train_file=${SQUAD_DIR}/train-v2.0.json \
  --predict_file=${SQUAD_DIR}/dev-v2.0.json \
  --uncased=False \
  --max_seq_length=512 \
  --do_train=False \
  --train_batch_size=48 \
  --do_predict=True \
  --predict_batch_size=32 \
  --learning_rate=3e-5 \
  --adam_epsilon=1e-6 \
  --iterations=1000 \
  --save_steps=1000 \
  --train_steps=8000 \
  --warmup_steps=1000 \
```

```
I0731 11:27:51.413786 140517151040960 estimator.py:209] Using config: {'_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true
, '_keep_checkpoint_max': 5, '_task_type': 'worker', '_train_distribute': None, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fcc8c59fd10>, '_model_dir': 'gs://uniquetestbucket/trained_xlnet/xlnet_cased_L-24_H-1024_A-16', '_protocol': None, '_save_checkpoints_steps': 1000, '_keep_checkpoint_every_n_hours': 10000, '_service': None, '_num_ps_replicas': 0, '_tpu_config': TPUConfig(iterations_per_loop=1000, num_shards=8, num_cores_per_replica=None, per_host_input_for_training=3, tpu_job_name=None, initial_infeed_sleep_secs=None, input_partition_dims=None, eval_training_input_configuration=2), '_tf_random_seed': None, '_save_summary_steps': 100, '_device_fn': None, '_cluster': None, '_experimental_distribute': None, '_num_worker_replicas': 1, '_task_id': 0, '_log_step_count_steps': None, '_experimental_max_worker_delay_secs': None, '_evaluation_master': u'grpc://10.240.1.2:8470', '_eval_distribute': None, '_global_id_in_cluster': 0, '_master': u'grpc://10.240.1.2:8470'}
I0731 11:27:51.414119 140517151040960 tpu_context.py:209] _TPUContext: eval_on_tpu True
W0731 11:27:51.414752 140517151040960 deprecation_wrapper.py:119] From run_squad.py:235: The name tf.gfile.Open is deprecated. Please use tf.io.gfile.GFile instead.

I0731 11:27:51.494606 140517151040960 run_squad.py:1228] Loading eval features from gs://uniquetestbucket/dataset/spiece.model.slen-512.qlen-64.eval.features.pkl
W0731 11:27:51.602171 140517151040960 deprecation_wrapper.py:119] From run_squad.py:927: The name tf.FixedLenFeature is deprecated. Please use tf.io.FixedLenFeature instead.

I0731 11:27:51.602550 140517151040960 run_squad.py:940] Input tfrecord file glob gs://uniquetestbucket/dataset/spiece.model.slen-512.qlen-64.eval.tf_record
W0731 11:27:51.602750 140517151040960 deprecation_wrapper.py:119] From run_squad.py:941: The name tf.gfile.Glob is deprecated. Please use tf.io.gfile.glob instead.

I0731 11:27:51.661521 140517151040960 run_squad.py:943] Find 1 input paths ['gs://uniquetestbucket/dataset/spiece.model.slen-512.qlen-64.eval.tf_record']
I0731 11:27:51.823481 140517151040960 tpu_system_metadata.py:78] Querying Tensorflow master (grpc://10.240.1.2:8470) for TPU system metadata.
2019-07-31 11:27:51.824941: W tensorflow/core/distributed_runtime/rpc/grpc_session.cc:356] GrpcSession::ListDevices will initialize the session with an empty graph and other defaults because the session has not yet been created.
I0731 11:27:51.829902 140517151040960 tpu_system_metadata.py:148] Found TPU system:
I0731 11:27:51.830167 140517151040960 tpu_system_metadata.py:149] *** Num TPU Cores: 8
I0731 11:27:51.830887 140517151040960 tpu_system_metadata.py:150] *** Num TPU Workers: 1
I0731 11:27:51.830991 140517151040960 tpu_system_metadata.py:152] *** Num TPU Cores Per Worker: 8
I0731 11:27:51.833934 140517151040960 estimator.py:1145] Calling model_fn.
W0731 11:27:51.862818 140517151040960 deprecation.py:323] From run_squad.py:1012: map_and_batch (from tensorflow.contrib.data.python.ops.batching) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.experimental.map_and_batch(...)`.
W0731 11:27:51.863205 140517151040960 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/contrib/data/python/ops/batching.py:273: map_and_batch (from tensorflow.python.data.experimental.ops.batching) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Dataset.map(map_func, num_parallel_calls)` followed by `tf.data.Dataset.batch(batch_size, drop_remainder)`. Static tf.data optimizations will take care of using the fused implementation.
W0731 11:27:51.865637 140517151040960 deprecation_wrapper.py:119] From run_squad.py:947: The name tf.parse_single_example is deprecated. Please use tf.io.parse_single_example instead.

W0731 11:27:52.111190 140517151040960 deprecation_wrapper.py:119] From /home/jb00557372/xlnet/xlnet.py:220: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

W0731 11:27:52.111473 140517151040960 deprecation_wrapper.py:119] From /home/jb00557372/xlnet/xlnet.py:220: The name tf.AUTO_REUSE is deprecated. Please use tf.compat.v1.AUTO_REUSE instead.

I0731 11:27:52.111825 140517151040960 modeling.py:453] memory input None
I0731 11:27:52.111964 140517151040960 modeling.py:455] Use float type <dtype: 'float32'>
W0731 11:27:52.211329 140517151040960 deprecation.py:323] From /home/jb00557372/xlnet/modeling.py:535: dropout (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dropout instead.
W0731 11:27:52.698326 140517151040960 deprecation.py:323] From /home/jb00557372/xlnet/modeling.py:67: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dense instead.
I0731 11:28:02.041882 140517151040960 run_squad.py:1030] #params: 364469250
I0731 11:28:02.042196 140517151040960 run_squad.py:1037] init_checkpoint not being used in predict mode.
I0731 11:28:02.955646 140517151040960 estimator.py:1147] Done calling model_fn.
I0731 11:28:02.960316 140517151040960 tpu_estimator.py:499] TPU job name tpu_worker
W0731 11:28:03.115952 140517151040960 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py:1354: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
I0731 11:28:03.651582 140517151040960 monitored_session.py:240] Graph was finalized.
W0731 11:28:03.652432 140517151040960 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
I0731 11:28:03.713215 140517151040960 saver.py:1280] Restoring parameters from gs://uniquetestbucket/trained_xlnet/xlnet_cased_L-24_H-1024_A-16/model.ckpt-8000
I0731 11:28:07.623855 140517151040960 session_manager.py:500] Running local_init_op.
I0731 11:28:08.152426 140517151040960 session_manager.py:502] Done running local_init_op.
W0731 11:28:08.820935 140517151040960 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py:808: load (from tensorflow.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Prefer Variable.assign which has equivalent behavior in 2.X.
I0731 11:28:09.349880 140517151040960 tpu_estimator.py:557] Init TPU system
I0731 11:28:15.887906 140517151040960 tpu_estimator.py:566] Initialized TPU in 6 seconds
I0731 11:28:15.889477 140516112979712 tpu_estimator.py:514] Starting infeed thread controller.
I0731 11:28:15.890222 140515894884096 tpu_estimator.py:533] Starting outfeed thread controller.
I0731 11:28:16.475498 140517151040960 util.py:98] Initialized dataset iterators in 0 seconds
I0731 11:28:17.015477 140517151040960 tpu_estimator.py:590] Enqueue next (1) batch(es) of data to infeed.
I0731 11:28:17.016248 140517151040960 tpu_estimator.py:594] Dequeue next (1) batch(es) of data from outfeed.
I0731 11:28:17.018121 140515894884096 tpu_estimator.py:275] Outfeed finished for iteration (0, 0)
I0731 11:28:40.663016 140517151040960 run_squad.py:1265] Processing example: 0
I0731 11:28:40.665004 140517151040960 tpu_estimator.py:590] Enqueue next (1) batch(es) of data to infeed.
I0731 11:28:40.665189 140517151040960 tpu_estimator.py:594] Dequeue next (1) batch(es) of data from outfeed.
I0731 11:28:40.810034 140517151040960 tpu_estimator.py:598] Stop infeed thread controller
I0731 11:28:40.810317 140517151040960 tpu_estimator.py:430] Shutting down InfeedController thread.
I0731 11:28:40.810642 140516112979712 tpu_estimator.py:425] InfeedController received shutdown signal, stopping.
I0731 11:28:40.810935 140516112979712 tpu_estimator.py:530] Infeed thread finished, shutting down.
I0731 11:28:40.811208 140517151040960 error_handling.py:96] infeed marked as finished
I0731 11:28:40.811455 140517151040960 tpu_estimator.py:602] Stop output thread controller
I0731 11:28:40.811517 140517151040960 tpu_estimator.py:430] Shutting down OutfeedController thread.
I0731 11:28:40.811672 140515894884096 tpu_estimator.py:425] OutfeedController received shutdown signal, stopping.
I0731 11:28:40.811765 140515894884096 tpu_estimator.py:541] Outfeed thread finished, shutting down.
I0731 11:28:40.811919 140517151040960 error_handling.py:96] outfeed marked as finished
I0731 11:28:40.812103 140517151040960 tpu_estimator.py:606] Shutdown TPU system.
I0731 11:28:41.660726 140517151040960 error_handling.py:96] prediction_loop marked as finished
I0731 11:28:41.661041 140517151040960 error_handling.py:96] prediction_loop marked as finished
I0731 11:28:41.661169 140517151040960 run_squad.py:735] Writing predictions to: predictions.json
W0731 11:28:41.661777 140517151040960 deprecation_wrapper.py:119] From run_squad.py:866: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.
Traceback (most recent call last):
  File "run_squad.py", line 1310, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "run_squad.py", line 1298, in main
    orig_data)
  File "run_squad.py", line 875, in write_predictions
    qid_to_has_ans = squad_utils.make_qid_to_has_ans(orig_data)
  File "/home/jb00557372/xlnet/squad_utils.py", line 42, in make_qid_to_has_ans
    qid_to_has_ans[qa['id']] = bool(qa['answers'])
KeyError: 'answers'
```

> init_checkpoint not being used in predict mode.

log shows up along with the key error.

**Comment by JeevaTM** [comment]
I made a new dataset for prediction which did not have answers key/value pair. It was predicting but the output directory for prediction is not mentioned in the flag 'predict_dir' so there was no output.

Setting the flag, 'predict-dir' and including 'Answers' in qas cleared the issue.
