### ISSUE TITLE
Issues with sentencepiece

### ISSUE THREAD

**Issue by Mahasweta-usc** [zihangdai/xlnet#237]
Run-classifier.py was running fine. Till I pretrained model and tried to use a checkpoint for fine tuning. 

python3  run_classifier.py   --use_tpu=True   --tpu=$TPU_NAME   --do_train=False   --do_eval=True   --eval_all_ckpt=False  --task_name=imdb   --data_dir=/home/user/xlnet/Data2   --output_dir=gs://user/data/output   --model_dir=gs://luser/data/MODEL_DIR --uncased=False   --spiece_model_path=/home/user/xlnet/$MODEL_DIR/spiece.model/   --model_config_path=gs://user/$MODEL_DIR/trained/config.json   --init_checkpoint=gs://user/$MODEL_DIR/trained/model.ckpt-19000   --max_seq_length=512   --train_batch_size=32   --eval_batch_size=8   --num_hosts=1   --num_core_per_host=8   --learning_rate=2e-5   --train_steps=8000   --warmup_steps=500   --save_steps=500   --iterations=500

Error:
filesystem.cc(48) LOG(ERROR) ReadAll is not supported for stdin.
Traceback (most recent call last):
  File "run_classifier.py", line 855, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_classifier.py", line 673, in main
    sp.Load(FLAGS.spiece_model_file)
  File "/usr/local/lib/python3.5/dist-packages/sentencepiece.py", line 118, in Load
    return _sentencepiece.SentencePieceProcessor_Load(self, filename)
RuntimeError: Internal: /sentencepiece/src/sentencepiece_processor.cc(49) [input->ReadAll(&proto)]

**Comment by CHASEXI** [comment]
I have the same error,can you tell me how to deal with it?

**Comment by DivyaWadehra** [comment]
I'm getting the same error, Please help in this
