### ISSUE TITLE
XLnet colab example error .

### ISSUE THREAD

**Issue by AlexTrinityBlock** [zihangdai/xlnet#292]
When I run XLnet colab example

https://github.com/zihangdai/xlnet/blob/master/notebooks/colab_imdb_gpu.ipynb

It showed the following error:

=========================

Traceback (most recent call last):
  File "xlnet/run_classifier.py", line 25, in <module>
    import model_utils
  File "/content/xlnet/model_utils.py", line 295, in <module>
    class AdamWeightDecayOptimizer(tf.train.Optimizer):
AttributeError: module 'tensorflow._api.v2.train' has no attribute 'Optimizer'

**Comment by AlexTrinityBlock** [comment]
Is Tensorflow 1. x  no longer supported on google colab ?

What should I do ?

If it's need conda for support Tensorflow 1. x , please tell me how to do that I can't finish it myself.
