### ISSUE TITLE
AttributeError: lr_layer_decay_rate

### ISSUE THREAD

**Issue by huseinzol05** [zihangdai/xlnet#30]
```
Traceback (most recent call last):
  File "train_gpu.py", line 328, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train_gpu.py", line 324, in main
    train("/gpu:0")
  File "train_gpu.py", line 258, in train
    grads_and_vars=grads_and_vars)
  File "/home/husein/xlnet/model_utils.py", line 147, in get_train_op
    if FLAGS.lr_layer_decay_rate != 1.0:
  File "/usr/local/lib/python3.6/dist-packages/absl/flags/_flagvalues.py", line 473, in __getattr__
    raise AttributeError(name)
AttributeError: lr_layer_decay_rate
```

For both [train.py](https://github.com/zihangdai/xlnet/blob/master/train.py) and [train_gpu.py](https://github.com/zihangdai/xlnet/blob/master/train_gpu.py). Both missing `lr_layer_decay_rate` from the `FLAGS`.

When I check [run_classifier.py](https://github.com/thomwolf/xlnet/blob/master/run_classifier.py),

```python
flags.DEFINE_float("lr_layer_decay_rate", 1.0,
                   "Top layer: lr[L] = FLAGS.learning_rate."
                   "Low layer: lr[l-1] = lr[l] * lr_layer_decay_rate.")
```

Default value is 1.0, but I am not sure the default value during pretraining is 1.0.

**Comment by zihangdai** [comment]
Thanks for pointing out this. This feature (`lr_layer_decay_rate`) was designed for the finetuning. We will fix this very soon.

**Comment by kimiyoung** [comment]
Fixed in https://github.com/zihangdai/xlnet/commit/8f17cfd59963a2c68fc76b00ac8f1d66e50b09ee
