### ISSUE TITLE
Getting the following error when trying to run tpu_squad_large.sh

### ISSUE THREAD

**Issue by rakshanda22** [zihangdai/xlnet#45]
```
W0624 16:40:52.848234 140595823699392 __init__.py:44] file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/__init__.py", line 41, in autodetect
    from . import file_cache
  File "/usr/local/lib/python2.7/dist-packages/googleapiclient/discovery_cache/file_cache.py", line 41, in <module>
    'file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth')
ImportError: file_cache is unavailable when using oauth2client >= 4.0.0 or google-auth
I0624 16:40:53.032814 140595823699392 model_utils.py:32] Use TPU without distribute strategy.
W0624 16:40:53.034595 140595823699392 estimator.py:1924] Estimator's model_fn (<function model_fn at 0x7fded610ded8>) includes params argument, but params are not passed to Estimator.
I0624 16:40:53.035511 140595823699392 estimator.py:201] Using config: {'_save_checkpoints_secs': None, '_session_config': allow_soft_placement: true
, '_keep_checkpoint_max': 5, '_task_type': 'worker', '_train_distribute': None, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fded610c2d0>, '_model_dir': 'gs://question-answering/experiment/squad', '_protocol': None, '_save_checkpoints_steps': 1000, '_keep_checkpoint_every_n_hours': 10000, '_service': None, '_num_ps_replicas': 0, '_tpu_config': TPUConfig(iterations_per_loop=1000, num_shards=8, num_cores_per_replica=None, per_host_input_for_training=3, tpu_job_name=None, initial_infeed_sleep_secs=None, input_partition_dims=None), '_tf_random_seed': None, '_save_summary_steps': 100, '_device_fn': None, '_cluster': None, '_experimental_distribute': None, '_num_worker_replicas': 1, '_task_id': 0, '_log_step_count_steps': None, '_evaluation_master': u'grpc://10.240.1.2:8470', '_eval_distribute': None, '_global_id_in_cluster': 0, '_master': u'grpc://10.240.1.2:8470'}
I0624 16:40:53.035886 140595823699392 tpu_context.py:202] _TPUContext: eval_on_tpu True
I0624 16:40:53.036292 140595823699392 run_squad.py:940] Input tfrecord file glob gs://question-answering/proc_data/squad/spiece.model.*.slen-512.qlen-64.train.tf_record
I0624 16:40:53.103672 140595823699392 run_squad.py:943] Find 0 input paths []
I0624 16:40:53.243366 140595823699392 tpu_system_metadata.py:59] Querying Tensorflow master (grpc://10.240.1.2:8470) for TPU system metadata.
2019-06-24 16:40:53.244997: W tensorflow/core/distributed_runtime/rpc/grpc_session.cc:354] GrpcSession::ListDevices will initialize the session with an empty graph and other defaults because the session has not yet been created.
I0624 16:40:53.250566 140595823699392 tpu_system_metadata.py:120] Found TPU system:
I0624 16:40:53.250852 140595823699392 tpu_system_metadata.py:121] *** Num TPU Cores: 8
I0624 16:40:53.251368 140595823699392 tpu_system_metadata.py:122] *** Num TPU Workers: 1
I0624 16:40:53.251487 140595823699392 tpu_system_metadata.py:124] *** Num TPU Cores Per Worker: 8
I0624 16:40:53.251578 140595823699392 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:CPU:0, CPU, -1, 13676165870058292740)
I0624 16:40:53.251995 140595823699392 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 17179869184, 18431886415160989968)
I0624 16:40:53.252130 140595823699392 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:0, TPU, 17179869184, 1709911759425913454)
I0624 16:40:53.252240 140595823699392 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:1, TPU, 17179869184, 10844450437283158931)
I0624 16:40:53.252331 140595823699392 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:2, TPU, 17179869184, 6304466678072412335)
I0624 16:40:53.252414 140595823699392 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:3, TPU, 17179869184, 1347834186282897648)
I0624 16:40:53.252512 140595823699392 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:4, TPU, 17179869184, 2010934665306124677)
I0624 16:40:53.252598 140595823699392 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:5, TPU, 17179869184, 1558411301377583255)
I0624 16:40:53.252691 140595823699392 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:6, TPU, 17179869184, 15582409736436553171)
I0624 16:40:53.252773 140595823699392 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU:7, TPU, 17179869184, 13427578911967334923)
I0624 16:40:53.252856 140595823699392 tpu_system_metadata.py:126] *** Available Device: _DeviceAttributes(/job:tpu_worker/replica:0/task:0/device:TPU_SYSTEM:0, TPU_SYSTEM, 17179869184, 17740777277430650014)
W0624 16:40:53.257469 140595823699392 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
I0624 16:40:53.268704 140595823699392 estimator.py:1111] Calling model_fn.
W0624 16:40:53.273418 140595823699392 deprecation.py:323] From run_squad.py:1001: parallel_interleave (from tensorflow.contrib.data.python.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.experimental.parallel_interleave(...)`.
I0624 16:40:53.275295 140595823699392 error_handling.py:70] Error recorded from training_loop: Tensor conversion requested dtype string for Tensor with dtype float32: 'Tensor("arg0:0", shape=(), dtype=float32, device=/job:tpu_worker/task:0/device:CPU:0)'
I0624 16:40:53.275455 140595823699392 error_handling.py:93] training_loop marked as finished
W0624 16:40:53.275588 140595823699392 error_handling.py:127] Reraising captured error
Traceback (most recent call last):
  File "run_squad.py", line 1310, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "run_squad.py", line 1209, in main
    estimator.train(input_fn=train_input_fn, max_steps=FLAGS.train_steps)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2457, in train
    rendezvous.raise_errors()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/error_handling.py", line 128, in raise_errors
    six.reraise(typ, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2452, in train
    saving_listeners=saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 358, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1124, in _train_model
return self._train_model_default(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1154, in _train_model_default
    features, labels, model_fn_lib.ModeKeys.TRAIN, self.config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2251, in _call_model_fn
    config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1112, in _call_model_fn
    model_fn_results = self._model_fn(features=features, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2547, in _model_fn
    input_holders.generate_infeed_enqueue_ops_and_dequeue_fn())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1167, in generate_infeed_enqueue_ops_and_dequeue_fn
    self._invoke_input_fn_and_record_structure())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 1243, in _invoke_input_fn_and_record_structure
    self._inputs_structure_recorder, host_device, host_id))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 830, in generate_per_host_v2_enqueue_ops_fn_for_host
    inputs = _Inputs.from_input_fn(input_fn(user_context))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/tpu/python/tpu/tpu_estimator.py", line 2423, in _input_fn
    return input_fn(**kwargs)
  File "run_squad.py", line 1001, in input_fn
    cycle_length=cycle_length))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1605, in apply
    return DatasetV1Adapter(super(DatasetV1, self).apply(transformation_func))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 1127, in apply
    dataset = transformation_func(self)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/data/experimental/ops/interleave_ops.py", line 88, in _apply_fn
    buffer_output_elements, prefetch_input_elements)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/data/ops/readers.py", line 133, in __init__
    cycle_length, block_length)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 2827, in __init__
    super(InterleaveDataset, self).__init__(input_dataset, map_func)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 2798, in __init__
    map_func, self._transformation_name(), dataset=input_dataset)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 2124, in __init__
    self._function.add_to_graph(ops.get_default_graph())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/function.py", line 490, in add_to_graph
    self._create_definition_if_needed()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/function.py", line 341, in _create_definition_if_needed
    self._create_definition_if_needed_impl()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/function.py", line 355, in _create_definition_if_needed_impl
    whitelisted_stateful_ops=self._whitelisted_stateful_ops)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/function.py", line 883, in func_graph_from_py_func
    outputs = func(*func_graph.inputs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 2099, in tf_data_structured_function_wrapper
    ret = func(*nested_args)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/data/ops/readers.py", line 247, in __init__
    filenames, compression_type, buffer_size, num_parallel_reads)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/data/ops/readers.py", line 199, in __init__
    filenames = ops.convert_to_tensor(filenames, dtype=dtypes.string)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1039, in convert_to_tensor
    return convert_to_tensor_v2(value, dtype, preferred_dtype, name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1097, in convert_to_tensor_v2
    as_ref=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1175, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 977, in _TensorTensorConversionFunction
    (dtype.name, t.dtype.name, str(t)))
ValueError: Tensor conversion requested dtype string for Tensor with dtype float32: 'Tensor("arg0:0", shape=(), dtype=float32, device=/job:tpu_worker/task:0/device:CPU:0)'
```

**Comment by kimiyoung** [comment]
```
I0624 16:40:53.036292 140595823699392 run_squad.py:940] Input tfrecord file glob gs://question-answering/proc_data/squad/spiece.model.*.slen-512.qlen-64.train.tf_record
I0624 16:40:53.103672 140595823699392 run_squad.py:943] Find 0 input paths []
```

This error results from not being able to find any input tf record files. Please make sure that you have preprocessed the data and used the correct `output_dir`.

**Comment by rakshanda22** [comment]
@kimiyoung Thanks 
My bad had not preprocessed the data
