### ISSUE TITLE
TypeError: Expected binary or unicode string, got None

### ISSUE THREAD

**Issue by aisheh90** [zihangdai/xlnet#95]
Hi
Did you try to predict using cola processor?
I am using the cola class processor (same as in BERT), it works fine for training and validation, but doesn't for test prediction and  got the following error:
TypeError: Expected binary or unicode string, got None

I am using the following command to predict:
--do_train=False
--do_eval=False 
--eval_split=test
--do_predict=True 
--task_name=cola

what is the possible problem?!

Thanks

**Comment by kimiyoung** [comment]
Could you provide the full stack trace?

**Comment by aisheh90** [comment]
Here is the full trace:
-------------------------
```
WARNING: Logging before flag parsing goes to stderr.
W0629 20:30:08.531441 140642042759040 deprecation_wrapper.py:119] From /content/drive/My Drive/mawdoo3/xlnet/xlnet/model_utils.py:293: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

W0629 20:30:08.539695 140642042759040 deprecation_wrapper.py:119] From run_classifier.py:1013: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

W0629 20:30:08.540431 140642042759040 deprecation_wrapper.py:119] From run_classifier.py:736: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

W0629 20:30:08.540586 140642042759040 deprecation_wrapper.py:119] From run_classifier.py:736: The name tf.logging.INFO is deprecated. Please use tf.compat.v1.logging.INFO instead.

W0629 20:30:08.540735 140642042759040 deprecation_wrapper.py:119] From run_classifier.py:744: The name tf.gfile.Exists is deprecated. Please use tf.io.gfile.exists instead.

Traceback (most recent call last):
  File "run_classifier.py", line 1013, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "run_classifier.py", line 744, in main
    if not tf.gfile.Exists(predict_dir):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 262, in file_exists
    return file_exists_v2(filename)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/lib/io/file_io.py", line 280, in file_exists_v2
    pywrap_tensorflow.FileExists(compat.as_bytes(path))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/compat.py", line 65, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got None


```

**Comment by lukemelas** [comment]
Hello @aisheh90, 

If you are trying to `do_predict`, you need to also remember to set `predict_dir` (another command-line argument). Are you currently passing something to `predict_dir`?

**Comment by aisheh90** [comment]
@lukemelas Thanks! I thought its like BERT that the output_dir is enough.

**Comment by GeetDsa** [comment]
@aisheh90 , Could you please share the code of Coda processor?

**Comment by aisheh90** [comment]
@GeetDsa yes sure, same as in issue #21

```
class ColaProcessor(GLUEProcessor):
  def __init__(self):
    super(ColaProcessor, self).__init__()
    self.label_column = 1
    self.text_a_column = 3
    self.test_text_a_column = 1

  def get_labels(self):
    return ["0", "1"]

  def _create_examples(self, lines, set_type):
    """Creates examples for the training and dev sets."""
    examples = []
    for (i, line) in enumerate(lines):
      if i == 0 and self.contains_header and set_type != "test":
        continue
      if i == 0 and self.test_contains_header and set_type == "test":
        continue
      guid = "%s-%s" % (set_type, i)

      a_column = (self.text_a_column if set_type != "test" else
          self.test_text_a_column)

      # there are some incomplete lines in QNLI
      if len(line) <= a_column:
        tf.logging.warning('Incomplete line, ignored.')
        continue
      text_a = line[a_column]

      if set_type == "test":
        label = self.get_labels()[0]
      else:
        if len(line) <= self.label_column:
          tf.logging.warning('Incomplete line, ignored.')
          continue
        label = line[self.label_column]
      examples.append(
          InputExample(guid=guid, text_a=text_a, text_b=None, label=label))
    return examples
```

**Comment by GeetDsa** [comment]
For me it worked on prediction, I mean it did not throw an error. However, did not get any valuable results.
